// IMPORTACION DE LA FUNCION HELPER DE VITE PARA TIPAR LA CONFIGURACION
import { defineConfig } from 'vite';
// IMPORTACION DEL PLUGIN OFICIAL DE TAILWIND CSS 4 PARA VITE
import tailwindcss from '@tailwindcss/vite';

// EXPORTACION POR DEFECTO DE LA CONFIGURACION DE VITE DEL PROYECTO ARGOS
export default defineConfig({
  // REGISTRO DEL PLUGIN DE TAILWIND CSS 4 EN EL PIPELINE DE VITE (NO USAMOS POSTCSS)
  plugins: [tailwindcss()],
});
