#!/bin/bash

REPO="21saul/PROYECTO_ARGOS_DAM2"

echo "CREANDO ETIQUETAS"

gh label create "CONFIGURACION"  --color "CCCCCC" --description "CONFIGURACION INICIAL DEL PROYECTO"  --repo $REPO --force
gh label create "FRONTEND"       --color "7C3AED" --description "TAREAS DEL FRONTEND"                --repo $REPO --force
gh label create "BACKEND"        --color "FF6B35" --description "TAREAS DEL BACKEND"                 --repo $REPO --force
gh label create "BASE DE DATOS"  --color "1CB0F6" --description "ESQUEMA Y MIGRACIONES"              --repo $REPO --force
gh label create "SEGURIDAD"      --color "EF4444" --description "AUTENTICACION Y CIFRADO"            --repo $REPO --force
gh label create "API"            --color "10B981" --description "ENDPOINTS REST"                     --repo $REPO --force
gh label create "BOVEDA"         --color "F59E0B" --description "MODULO BOVEDA CIFRADA"              --repo $REPO --force
gh label create "AUDITOR"        --color "06B6D4" --description "MODULO AUDITOR DIGITAL"             --repo $REPO --force
gh label create "PHISHING"       --color "EC4899" --description "MODULO ANALIZADOR DE PHISHING"      --repo $REPO --force
gh label create "NOTICIAS"       --color "003C71" --description "PANEL DE NOTICIAS Y ALERTAS"        --repo $REPO --force
gh label create "ROADMAP"        --color "A78BFA" --description "ITINERARIO FORMATIVO"               --repo $REPO --force
gh label create "AUTOMATIZACION" --color "88CC14" --description "FLUJOS N8N"                         --repo $REPO --force
gh label create "INTEGRACION"    --color "4C1D95" --description "CONEXION ENTRE FRONTEND Y BACKEND"  --repo $REPO --force
gh label create "DOCUMENTACION"  --color "BBF7D0" --description "DOCUMENTACION TECNICA"              --repo $REPO --force
gh label create "TESTING"        --color "6B7280" --description "TESTS Y CALIDAD DE CODIGO"          --repo $REPO --force

echo "CREANDO HITOS DE PROYECTO"

gh api -X POST "repos/$REPO/milestones" -f title="SPRINT 0 - PROTOTIPADO INICIAL DEL FRONTEND"           -f description="MAQUETACION COMPLETA DE LA APLICACION FRONTEND"      --silent
gh api -X POST "repos/$REPO/milestones" -f title="SPRINT 1 - INFRAESTRUCTURA DEL BACKEND"                -f description="ENTORNO DE DESARROLLO Y BASE DEL BACKEND"           --silent
gh api -X POST "repos/$REPO/milestones" -f title="SPRINT 2 - AUTENTICACION Y SEGURIDAD"                  -f description="JWT, DOBLE FACTOR Y ESQUEMA DE DATOS"               --silent
gh api -X POST "repos/$REPO/milestones" -f title="SPRINT 3 - API REST DE LA BOVEDA"                      -f description="ENDPOINTS DE LA BOVEDA Y CARPETAS"                  --silent
gh api -X POST "repos/$REPO/milestones" -f title="SPRINT 4 - APIS DEL AUDITOR Y PHISHING"                -f description="PROXIES A SERVICIOS EXTERNOS"                       --silent
gh api -X POST "repos/$REPO/milestones" -f title="SPRINT 5 - PANEL DE NOTICIAS Y AUTOMATIZACION"         -f description="N8N, NVD Y FEEDS RSS"                               --silent
gh api -X POST "repos/$REPO/milestones" -f title="SPRINT 6 - INTEGRACION FRONTEND-BACKEND Y TESTING"     -f description="CONEXION COMPLETA, TESTS Y AUDITORIAS DE SEGURIDAD" --silent

echo "CREANDO ISSUES DEL SPRINT 0 - PROTOTIPADO DEL FRONTEND"

gh issue create --repo $REPO --title "[FRONTEND] CONFIGURACION INICIAL DE IONIC 8 Y ANGULAR 20" --body "INICIALIZACION DEL PROYECTO IONIC CON ANGULAR 20, CONFIGURACION DE CAPACITOR 6 Y MIGRACION DEL BUILDER A ESBUILD." --label "FRONTEND,CONFIGURACION" --milestone "SPRINT 0 - PROTOTIPADO INICIAL DEL FRONTEND"

gh issue create --repo $REPO --title "[FRONTEND] SISTEMA DE DISENO Y TOKENS VISUALES" --body "PALETA DUAL CLARO Y OSCURO, TIPOGRAFIA BRICOLAGE GROTESQUE Y INTER, TOKENS CSS Y SISTEMA DE ELEVACION." --label "FRONTEND" --milestone "SPRINT 0 - PROTOTIPADO INICIAL DEL FRONTEND"

gh issue create --repo $REPO --title "[FRONTEND] PANTALLAS DE LOGIN, REGISTRO Y BIENVENIDA" --body "FLUJO COMPLETO DE ENTRADA A LA APLICACION CON TRES SLIDES DE BIENVENIDA, LOGIN Y REGISTRO." --label "FRONTEND" --milestone "SPRINT 0 - PROTOTIPADO INICIAL DEL FRONTEND"

gh issue create --repo $REPO --title "[FRONTEND] PANTALLA PRINCIPAL CON TARJETA DE PUNTUACION" --body "PANTALLA PRINCIPAL CON TARJETA HERO DE PUNTUACION DE PRIVACIDAD, INDICADORES Y CUADRICULA DE MODULOS." --label "FRONTEND" --milestone "SPRINT 0 - PROTOTIPADO INICIAL DEL FRONTEND"

gh issue create --repo $REPO --title "[FRONTEND] MODULO BOVEDA CON CARPETAS Y BOTON FLOTANTE" --body "GESTION DE CONTRASENAS, NOTAS Y ARCHIVOS CON CARPETAS, BUSQUEDA Y BOTON DE ACCION FLOTANTE EXPANDIBLE." --label "FRONTEND,BOVEDA" --milestone "SPRINT 0 - PROTOTIPADO INICIAL DEL FRONTEND"

gh issue create --repo $REPO --title "[FRONTEND] MODULO AUDITOR CON PUNTUACION DE PRIVACIDAD" --body "PANEL CON PUNTUACION CIRCULAR ANIMADA, EVOLUCION TEMPORAL, PILARES DE SEGURIDAD Y AMENAZAS ACTIVAS." --label "FRONTEND,AUDITOR" --milestone "SPRINT 0 - PROTOTIPADO INICIAL DEL FRONTEND"

gh issue create --repo $REPO --title "[FRONTEND] MODULO ANALIZADOR DE PHISHING" --body "ANALIZADOR DE URLS CON PIPELINE VISUAL DE CUATRO MOTORES, MAPA DE OBJETIVOS Y EJEMPLOS COMPARATIVOS." --label "FRONTEND,PHISHING" --milestone "SPRINT 0 - PROTOTIPADO INICIAL DEL FRONTEND"

gh issue create --repo $REPO --title "[FRONTEND] MODULO ROADMAP GAMIFICADO" --body "MAPA DE NODOS TRIDIMENSIONALES ESTILO DUOLINGO CON CINCO ITINERARIOS Y SISTEMA DE GAMIFICACION." --label "FRONTEND,ROADMAP" --milestone "SPRINT 0 - PROTOTIPADO INICIAL DEL FRONTEND"

gh issue create --repo $REPO --title "[FRONTEND] PANEL DE NOTICIAS Y VULNERABILIDADES" --body "PANEL DE INTELIGENCIA DE AMENAZAS CON CARRUSEL DE FUENTES, TARJETAS DESTACADAS Y FILTROS POR CATEGORIA." --label "FRONTEND,NOTICIAS" --milestone "SPRINT 0 - PROTOTIPADO INICIAL DEL FRONTEND"

gh issue create --repo $REPO --title "[FRONTEND] MASCOTA ARGUS Y OJO FLOTANTE ARRASTRABLE" --body "MASCOTA SVG INSPIRADA EN EL TITAN MITOLOGICO DE LOS CIEN OJOS Y OJO FLOTANTE COMPANERO ARRASTRABLE QUE OFRECE CONSEJOS DE CIBERSEGURIDAD." --label "FRONTEND" --milestone "SPRINT 0 - PROTOTIPADO INICIAL DEL FRONTEND"

echo "CREANDO ISSUES DEL SPRINT 1 - INFRAESTRUCTURA BACKEND"

gh issue create --repo $REPO --title "[BACKEND] CONFIGURAR ENTORNO DE DESARROLLO CON DDEV" --body "INICIALIZAR DDEV EN LA CARPETA DEL BACKEND CON PHP 8.2 Y MARIADB 10.11. CREAR EL ARCHIVO DE CONFIGURACION Y VERIFICAR QUE EL DOMINIO LOCAL RESUELVE." --label "BACKEND,CONFIGURACION" --milestone "SPRINT 1 - INFRAESTRUCTURA DEL BACKEND"

gh issue create --repo $REPO --title "[BACKEND] INSTALAR Y CONFIGURAR CODEIGNITER 4" --body "INSTALAR CODEIGNITER 4 MEDIANTE COMPOSER. VERIFICAR LA PAGINA DE BIENVENIDA. CONFIGURAR LA URL BASE Y EL IDIOMA POR DEFECTO EN ESPANOL." --label "BACKEND,CONFIGURACION" --milestone "SPRINT 1 - INFRAESTRUCTURA DEL BACKEND"

gh issue create --repo $REPO --title "[BACKEND] ESTRUCTURA DE CARPETAS Y CONVENCIONES DE CODIGO" --body "CREAR LA ESTRUCTURA DE CARPETAS PARA CONTROLADORES, MODELOS, SERVICIOS Y FILTROS. DEFINIR LAS CONVENCIONES DE COMENTARIOS LINEA POR LINEA EN MAYUSCULAS." --label "BACKEND,DOCUMENTACION" --milestone "SPRINT 1 - INFRAESTRUCTURA DEL BACKEND"

echo "CREANDO ISSUES DEL SPRINT 2 - AUTENTICACION Y SEGURIDAD"

gh issue create --repo $REPO --title "[BACKEND] INTEGRAR CODEIGNITER SHIELD PARA AUTENTICACION JWT" --body "INSTALAR LA LIBRERIA SHIELD MEDIANTE COMPOSER, PUBLICAR LA CONFIGURACION, CONFIGURAR JWT COMO PROVEEDOR PRINCIPAL Y EJECUTAR LAS MIGRACIONES." --label "BACKEND,SEGURIDAD" --milestone "SPRINT 2 - AUTENTICACION Y SEGURIDAD"

gh issue create --repo $REPO --title "[BACKEND] DISENAR ESQUEMA DE BASE DE DATOS ZERO-KNOWLEDGE" --body "CREAR LAS MIGRACIONES PARA LAS TABLAS DE USUARIOS, ELEMENTOS DE LA BOVEDA, CARPETAS, REGISTROS DE AUDITORIA Y CACHE DE NOTICIAS. DOCUMENTAR EL ESQUEMA COMPLETO." --label "BACKEND,BASE DE DATOS" --milestone "SPRINT 2 - AUTENTICACION Y SEGURIDAD"

gh issue create --repo $REPO --title "[BACKEND] IMPLEMENTAR DOBLE FACTOR DE AUTENTICACION CON TOTP" --body "ANADIR SOPORTE TOTP A SHIELD. ENDPOINT PARA GENERAR EL CODIGO QR DE CONFIGURACION Y VALIDAR LOS CODIGOS DE SEIS DIGITOS." --label "BACKEND,SEGURIDAD" --milestone "SPRINT 2 - AUTENTICACION Y SEGURIDAD"

echo "CREANDO ISSUES DEL SPRINT 3 - API REST DE LA BOVEDA"

gh issue create --repo $REPO --title "[API] ENDPOINT DE REGISTRO DE USUARIOS" --body "RECIBIR EMAIL, HASH DE VERIFICACION Y BLOQUE CIFRADO INICIAL DERIVADO CON ARGON2ID EN EL CLIENTE. NUNCA RECIBIR LA CONTRASENA EN TEXTO PLANO." --label "BACKEND,API,BOVEDA" --milestone "SPRINT 3 - API REST DE LA BOVEDA"

gh issue create --repo $REPO --title "[API] ENDPOINT DE LOGIN DE USUARIOS" --body "VALIDAR LAS CREDENCIALES DERIVADAS, DEVOLVER UN TOKEN JWT JUNTO CON EL BLOQUE CIFRADO DE LA BOVEDA PARA QUE EL CLIENTE LO DESCIFRE LOCALMENTE." --label "BACKEND,API,BOVEDA" --milestone "SPRINT 3 - API REST DE LA BOVEDA"

gh issue create --repo $REPO --title "[API] CRUD DE ELEMENTOS DE LA BOVEDA" --body "OPERACIONES DE LECTURA, CREACION, ACTUALIZACION Y BORRADO DE ELEMENTOS. EL SERVIDOR SOLO RECIBE BLOQUES CIFRADOS OPACOS. AUTENTICACION OBLIGATORIA MEDIANTE JWT." --label "BACKEND,API,BOVEDA" --milestone "SPRINT 3 - API REST DE LA BOVEDA"

gh issue create --repo $REPO --title "[API] CRUD DE CARPETAS DE LA BOVEDA" --body "OPERACIONES SOBRE CARPETAS. METADATOS EN CLARO COMO EL NOMBRE, COLOR E ICONO. LOS ELEMENTOS DENTRO SIGUEN CIFRADOS." --label "BACKEND,API,BOVEDA" --milestone "SPRINT 3 - API REST DE LA BOVEDA"

echo "CREANDO ISSUES DEL SPRINT 4 - AUDITOR Y PHISHING"

gh issue create --repo $REPO --title "[API] PROXY A HAVE I BEEN PWNED CON K-ANONYMITY" --body "ENDPOINT QUE RECIBE LOS CINCO PRIMEROS CARACTERES DEL HASH SHA-1, CONSULTA LA API DE HAVE I BEEN PWNED, CACHEA LA RESPUESTA Y DEVUELVE LA LISTA DE HASHES COINCIDENTES." --label "BACKEND,API,AUDITOR" --milestone "SPRINT 4 - APIS DEL AUDITOR Y PHISHING"

gh issue create --repo $REPO --title "[API] HISTORICO DE LA PUNTUACION DE PRIVACIDAD" --body "ENDPOINT POST PARA GUARDAR LA PUNTUACION DEL DIA EN LA BASE DE DATOS. ENDPOINT GET PARA RECUPERAR EL HISTORICO DE LAS ULTIMAS OCHO SEMANAS." --label "BACKEND,API,AUDITOR" --milestone "SPRINT 4 - APIS DEL AUDITOR Y PHISHING"

gh issue create --repo $REPO --title "[API] PROXY A GOOGLE SAFE BROWSING" --body "ENDPOINT QUE RECIBE UNA URL, CONSULTA LA API DE GOOGLE SAFE BROWSING Y DEVUELVE EL VEREDICTO NORMALIZADO." --label "BACKEND,API,PHISHING" --milestone "SPRINT 4 - APIS DEL AUDITOR Y PHISHING"

gh issue create --repo $REPO --title "[API] PROXY A PHISHTANK" --body "ENDPOINT QUE CONSULTA PHISHTANK CON CACHE EN LA BASE DE DATOS PARA NO AGOTAR LOS LIMITES DE TASA DEL SERVICIO." --label "BACKEND,API,PHISHING" --milestone "SPRINT 4 - APIS DEL AUDITOR Y PHISHING"

gh issue create --repo $REPO --title "[API] PROXY A VIRUSTOTAL" --body "ENDPOINT QUE CONSULTA VIRUSTOTAL CON LIMITACION DE TASA INTERNA. EL PLAN GRATUITO PERMITE CUATRO PETICIONES POR MINUTO Y QUINIENTAS AL DIA." --label "BACKEND,API,PHISHING" --milestone "SPRINT 4 - APIS DEL AUDITOR Y PHISHING"

echo "CREANDO ISSUES DEL SPRINT 5 - NOTICIAS Y AUTOMATIZACION"

gh issue create --repo $REPO --title "[AUTOMATIZACION] CONFIGURAR N8N EN ENTORNO LOCAL" --body "LEVANTAR N8N EN UN CONTENEDOR DOCKER AISLADO EN LOCALHOST. CONFIGURAR LAS CREDENCIALES DEL NVD Y DESHABILITAR LOS WEBHOOKS NO UTILIZADOS." --label "AUTOMATIZACION,NOTICIAS" --milestone "SPRINT 5 - PANEL DE NOTICIAS Y AUTOMATIZACION"

gh issue create --repo $REPO --title "[AUTOMATIZACION] FLUJO DE CONSUMO DE LA API DEL NVD" --body "TAREA PROGRAMADA QUE CONSULTA LAS VULNERABILIDADES CRITICAS FILTRADAS POR PRODUCTOS DOMESTICOS Y LAS ALMACENA EN LA TABLA DE CACHE DE NOTICIAS." --label "AUTOMATIZACION,NOTICIAS" --milestone "SPRINT 5 - PANEL DE NOTICIAS Y AUTOMATIZACION"

gh issue create --repo $REPO --title "[AUTOMATIZACION] FLUJO DE CONSUMO DE FEEDS RSS" --body "TAREA PROGRAMADA QUE LEE LOS FEEDS DE INCIBE, HISPASEC, BLEEPINGCOMPUTER Y THE HACKER NEWS, LOS NORMALIZA AL ESQUEMA COMUN Y LOS ALMACENA EN LA CACHE." --label "AUTOMATIZACION,NOTICIAS" --milestone "SPRINT 5 - PANEL DE NOTICIAS Y AUTOMATIZACION"

gh issue create --repo $REPO --title "[API] ENDPOINT DE NOTICIAS" --body "DEVUELVE LAS NOTICIAS DE LA CACHE PAGINADAS Y FILTRABLES POR CATEGORIA. INCLUYE ESTADISTICAS DEL DIA COMO VULNERABILIDADES PUBLICADAS, PUNTUACION MEDIA Y FUENTES ACTIVAS." --label "BACKEND,API,NOTICIAS" --milestone "SPRINT 5 - PANEL DE NOTICIAS Y AUTOMATIZACION"

echo "CREANDO ISSUES DEL SPRINT 6 - INTEGRACION Y TESTING"

gh issue create --repo $REPO --title "[INTEGRACION] CONECTAR LOGIN DEL FRONTEND CON EL BACKEND" --body "REEMPLAZAR EL MOCK DE LOGIN POR LA LLAMADA REAL AL ENDPOINT DEL BACKEND. GUARDAR EL TOKEN JWT EN EL ALMACENAMIENTO SEGURO DE CAPACITOR." --label "FRONTEND,INTEGRACION" --milestone "SPRINT 6 - INTEGRACION FRONTEND-BACKEND Y TESTING"

gh issue create --repo $REPO --title "[INTEGRACION] CONECTAR BOVEDA CON LA API REAL" --body "SUSTITUIR EL ARRAY DE PRUEBA DE ELEMENTOS POR LLAMADAS AL BACKEND. IMPLEMENTAR EL CIFRADO Y DESCIFRADO LOCAL EN ANGULAR ANTES Y DESPUES DE CADA LLAMADA." --label "FRONTEND,INTEGRACION,BOVEDA" --milestone "SPRINT 6 - INTEGRACION FRONTEND-BACKEND Y TESTING"

gh issue create --repo $REPO --title "[INTEGRACION] CONECTAR AUDITOR CON LA API REAL" --body "LLAMADAS REALES A HAVE I BEEN PWNED A TRAVES DEL BACKEND Y AL ENDPOINT DE PUNTUACION DE PRIVACIDAD PARA LA EVOLUCION HISTORICA." --label "FRONTEND,INTEGRACION,AUDITOR" --milestone "SPRINT 6 - INTEGRACION FRONTEND-BACKEND Y TESTING"

gh issue create --repo $REPO --title "[INTEGRACION] CONECTAR PANEL DE NOTICIAS CON LA CACHE REAL" --body "SUSTITUIR EL ARRAY DE PRUEBA DE NOTICIAS POR LLAMADAS AL ENDPOINT DEL BACKEND." --label "FRONTEND,INTEGRACION,NOTICIAS" --milestone "SPRINT 6 - INTEGRACION FRONTEND-BACKEND Y TESTING"

gh issue create --repo $REPO --title "[TESTING] TESTS UNITARIOS DEL BACKEND" --body "COBERTURA OBJETIVO MINIMA DEL SETENTA POR CIENTO. PRIORIZAR CONTROLADORES DE AUTENTICACION, CRUD DE LA BOVEDA Y SERVICIOS DE PROXY A APIS EXTERNAS." --label "TESTING,BACKEND" --milestone "SPRINT 6 - INTEGRACION FRONTEND-BACKEND Y TESTING"

gh issue create --repo $REPO --title "[DOCUMENTACION] ESPECIFICACION OPENAPI DE LA API" --body "GENERAR LA ESPECIFICACION OPENAPI 3.0 DE TODOS LOS ENDPOINTS DEL BACKEND. PUBLICAR LA INTERFAZ SWAGGER UI EN UNA RUTA DEDICADA." --label "DOCUMENTACION,BACKEND" --milestone "SPRINT 6 - INTEGRACION FRONTEND-BACKEND Y TESTING"

gh issue create --repo $REPO --title "[SEGURIDAD] AUDITORIA DE SEGURIDAD CON OWASP ZAP" --body "EJECUTAR EL ESCANEO AUTOMATICO DE OWASP ZAP CONTRA EL BACKEND EN LOCAL. DOCUMENTAR LOS HALLAZGOS Y LAS MEDIDAS DE MITIGACION APLICADAS." --label "SEGURIDAD,TESTING" --milestone "SPRINT 6 - INTEGRACION FRONTEND-BACKEND Y TESTING"

echo "PROCESO COMPLETADO"
echo "RESUMEN:"
echo "- 15 ETIQUETAS CREADAS"
echo "- 7 HITOS DE PROYECTO CREADOS"
echo "- 33 ISSUES CREADOS EN TOTAL"
echo ""
echo "PROXIMOS PASOS:"
echo "1. CIERRA MANUALMENTE LOS 10 ISSUES DEL SPRINT 0 (FRONTEND YA TERMINADO)"
echo "2. CREA EL TABLERO KANBAN EN LA PESTANA PROJECTS DE GITHUB"
echo "3. ANADE TODOS LOS ISSUES AL TABLERO Y EMPIEZA POR EL PRIMERO DEL SPRINT 1"
