// AUTH GUARD
//
// RESUMEN: GUARD FUNCIONAL (CanActivateFn) QUE PROTEGE LAS RUTAS QUE
// REQUIEREN UNA SESION ZERO-KNOWLEDGE COMPLETAMENTE OPERATIVA.
//
// LOGICA DE NEGOCIO: PERMITE EL ACCESO SOLO SI hasLiveSession() ES TRUE,
// ES DECIR, SI EXISTE JWT *Y* LA CLAVE DE CIFRADO SIGUE EN MEMORIA. TRAS
// UN HARD-REFRESH EL JWT PERSISTE EN localStorage PERO LA CLAVE SE PIERDE
// (NUNCA SE GUARDA EN DISCO POR DISENO), DEJANDO LA APP EN UN ESTADO ROTO
// DONDE LA BOVEDA NO PUEDE DESCIFRARSE Y, SI EL TOKEN HA CADUCADO, LAS
// LLAMADAS A LA API DEVUELVEN 401. EN ESE CASO REDIRIGIMOS A /login PARA
// QUE EL USUARIO RE-DERIVE LA CLAVE Y OBTENGA UN TOKEN FRESCO.
//
// RELACIONES:
// - AuthService (hasLiveSession)
// - app-routing.module.ts (canActivate de las rutas protegidas)

// IMPORTACION DE LOS TIPOS Y UTILIDADES DEL ROUTER DE ANGULAR
import { CanActivateFn, Router } from '@angular/router';
// IMPORTACION DEL INYECTOR FUNCIONAL PARA RESOLVER DEPENDENCIAS EN EL GUARD
import { inject } from '@angular/core';
// IMPORTACION DEL SERVICIO DE AUTENTICACION QUE EXPONE hasLiveSession()
import { AuthService } from '../services/auth.service';

// GUARD QUE AUTORIZA O BLOQUEA EL ACCESO A UNA RUTA PROTEGIDA
export const authGuard: CanActivateFn = () => {
  // RESUELVE EL SERVICIO DE AUTENTICACION DEL INYECTOR DE ANGULAR
  const auth = inject(AuthService);
  // RESUELVE EL ROUTER PARA PODER REDIRIGIR SI NO HAY SESION VIVA
  const router = inject(Router);

  // SI LA SESION ESTA VIVA (TOKEN + CLAVE EN MEMORIA) PERMITIMOS EL ACCESO
  if (auth.hasLiveSession()) {
    return true;
  }

  // SIN SESION VIVA: REDIRIGIMOS AL LOGIN PARA RE-AUTENTICAR Y BLOQUEAMOS LA RUTA
  return router.createUrlTree(['/login']);
};
