// ENVIRONMENT (PRODUCCION)
//
// RESUMEN: VARIABLES DE ENTORNO PARA EL BUILD DE PRODUCCION DEL
// FRONTEND IONIC. EXPONE LA URL BASE DEL BACKEND ARGOS QUE
// CONSUME EL ApiService EN EL ENTORNO DESPLEGADO.
//
// NOTA: ANGULAR REEMPLAZA environment.ts POR ESTE ARCHIVO EN
// BUILDS DE PRODUCCION (CONFIGURADO EN angular.json).

export const environment = {
  // FLAG DE PRODUCCION ACTIVADO
  production: true,

  // URL BASE DEL BACKEND - APUNTA A LA IP LAN DEL HOST DE DESARROLLO
  // PUERTO 8080 FIJADO EN .ddev/config.yaml PARA QUE NO CAMBIE EN CADA REINICIO
  // EL MOVIL DEBE ESTAR EN LA MISMA RED WIFI QUE EL HOST PARA ALCANZARLO
  apiBaseUrl: 'http://192.168.1.137:8080/api/v1',
};
